from .base_command import BaseCommand
from .cogview2 import CogView2
from .dalle_mini import DalleMini
from .dalle_mega import DalleMega
from .latent_diffusion import LatentDiffusion
from .erlich import Erlich
from .davinci import Davinci
from .rinna_gpt2m import RinnaGpt2Medium
from .stable_diffusion import StableDiffusion
