import os


class Config:
    HUGGINGFACE_API_TOKEN = os.environ["HUGGINGFACE_API_TOKEN"]
    REPLICATE_API_TOKEN = os.environ["REPLICATE_API_TOKEN"]
    SLACK_BOT_OAUTH_TOKEN = os.environ["SLACK_BOT_OAUTH_TOKEN"]
    SLACK_VERIFICATION_TOKEN = os.environ["SLACK_VERIFICATION_TOKEN"]
